import Head from "next/head";
import { CodeInOut, CodeInline } from "../components/code.block";
import Link from "next/link";
// prettier-ignore
export default function Home() {
  return (
    <div>
      <Head>
        <title>Python Notebbok</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Link href='/data-types/string'><a>Data types</a></Link>
        <CodeInOut codeIn={code} codeOut={`Hello`}>
        <h1>hello world</h1>
         <p>
         hello <CodeInline code={`5^2`}/> hey
        </p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti, laudantium.</p>
        </CodeInOut>

      </main>
    </div>
  );
}

const code = `from tkinter import *

# ---------------------------- CONSTANTS ------------------------------- #
PINK = "#e2979c"
RED = "#e7305b"
GREEN = "#9bdeac"
YELLOW = "#f7f5dd"
BLACK = "#000000"
FONT_NAME = "Courier"
WORK_MIN = 25
SHORT_BREAK_MIN = 5
LONG_BREAK_MIN = 20

# ---------------------------- TIMER RESET ------------------------------- #

# ---------------------------- TIMER MECHANISM ------------------------------- #

# ---------------------------- COUNTDOWN MECHANISM ------------------------------- #

# ---------------------------- UI SETUP ------------------------------- #
# start tkinter
window = Tk()
# window  Title
window.title("Pomodoro")
# window min size
window.minsize(width=200, height=200)
window.config(padx=100, pady=50, bg=YELLOW)


#canvas
canvas = Canvas(width=200, height=200, bg=YELLOW, highlightthickness=0)
item_text = canvas.create_text(100, 100, text='00:00', font=(FONT_NAME, 35, 'bold'))
canvas.grid(column=1, row=1)
canvas.itemconfig(item_text,text='hello') #itemconfig(the item i want to change, what i want to change in the item)
# keep the window open
window.mainloop()
`;
